Controllers/MethodsController.cs
using DrugMMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;

namespace DrugMMvc.Controllers
{
    public class MethodsController : Controller
    {
        string baseURL = "https://localhost:7289/";

        [NoDirectAccess]

        public async Task<IActionResult> AddCart(int id)
        {
            TempData["id"] = id;
            List<Product> p = new List<Product>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("https://localhost:7289/api/Products");
                if (res.IsSuccessStatusCode)
                {
                    var Prodres = res.Content.ReadAsStringAsync().Result;
                    p = JsonConvert.DeserializeObject<List<Product>>(Prodres);
                }

                foreach (var a in p)
                {
                    if (a.ProductId == id)
                    {
                        HttpContext.Session.SetString("Name", a.ProductName);

                        ViewBag.ProductName = a.ProductName;
                        ViewBag.Price = a.Price;
                        ViewBag.Stock = a.Stock;
                        ViewBag.ProductId = a.ProductId;

                    }
                }

                Product p1 = new Product();
                //HttpContext.Session.SetInt32("stock", (int)p1.Stock);
                p1.ProductId = id;
                return View(p1);
            }
        }

        [NoDirectAccess]

        [HttpPost]


        public async Task<IActionResult> AddCart(Product p)
        {

            OrderDetail? O = new OrderDetail();
            O.UserId = (int)HttpContext.Session.GetInt32("id");
            O.ProductId = p.ProductId;

            O.ProductId = (int)TempData["id"];
            //int id = (int)TempData["id"];
            //O.ProductId = id;
            O.Quantity = p.Stock;

            O.PurchaseId = null;

            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(baseURL);
                StringContent content = new StringContent(JsonConvert.SerializeObject(O), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("https://localhost:7289/api/Methods", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    O = JsonConvert.DeserializeObject<OrderDetail>(apiResponse);
                }
            }
            return RedirectToAction("Cart");
        }
        [NoDirectAccess]

        public async Task<IActionResult> Cart()
        {
            int id = (int)HttpContext.Session.GetInt32("id");
            List<OrderDetail> p = new List<OrderDetail>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("https://localhost:7289/api/Methods/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var Prodres = res.Content.ReadAsStringAsync().Result;
                    p = JsonConvert.DeserializeObject<List<OrderDetail>>(Prodres);
                }
            }

            List<Product> p1 = new List<Product>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("https://localhost:7289/api/Products");
                if (res.IsSuccessStatusCode)
                {
                    var Prodres = res.Content.ReadAsStringAsync().Result;
                    p1 = JsonConvert.DeserializeObject<List<Product>>(Prodres);
                }
            }

            // List<OrderDetail> p4 = p.ToList(i => i.PurchaseId == null);
            //List<OrderDetail> p4= new List<OrderDetail>();
            //foreach (var item in p)
            //{
            //    p4= p.ToList(i => i.PurchaseId==null);

            //}




            foreach (var n in p)
            {
                if (n.PurchaseId == null)
                {
                    var p2 = p1.FirstOrDefault(i => i.ProductId == n.ProductId);
                    n.ProductName = p2.ProductName;
                    n.UnitPrice = p2.Price;
                }
                else
                {
                    n.Quantity = null;
                }
            }
            Nullable<int> t = 0;
            foreach (var n1 in p)
            {
                if (n1.PurchaseId == null)
                {
                    t += (n1.UnitPrice * n1.Quantity);
                }
            }

            ViewBag.Total = t;
            HttpContext.Session.SetInt32("t", (int)t);
            return View(p);
        }


        //[HttpGet]
        //public async Task<IActionResult> Delete(int id)
        //{
        //    OrderDetail o = new OrderDetail();
        //    TempData["id"] = id;
        //    using (var client = new HttpClient())
        //    {
        //        using (var res = await client.GetAsync("https://localhost:7289/api//" + id))
        //        {
        //            string apir = await res.Content.ReadAsStringAsync();
        //            o = JsonConvert.DeserializeObject<OrderDetail>(apir);
        //        }
        //    }
        //    return View(o);

        //}

        [NoDirectAccess]

        public async Task<IActionResult> Delete(int OrderId)
        {

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURL);
                await client.DeleteAsync("https://localhost:7289/api/Methods/" + OrderId);
            }
            return RedirectToAction("Index", "Calling");
        }

        [NoDirectAccess]

        public async Task<IActionResult> Buy()
        {
            ViewBag.Total = HttpContext.Session.GetInt32("t");
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Location = HttpContext.Session.GetString("Location");
            ViewBag.PhNum = HttpContext.Session.GetString("PhoneNumber");
            ViewBag.EmailId = HttpContext.Session.GetString("EmailId");
            return View();

        }

        [NoDirectAccess]

        [HttpPost]
        public async Task<IActionResult> Buy(Buyer buyer)
        {
            buyer.DateofPurchase = DateTime.Now;
            buyer.TotalAmount = HttpContext.Session.GetInt32("t");
            buyer.UserId = (int)HttpContext.Session.GetInt32("id");
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(buyer), Encoding.UTF8, "application/json");
                var response = await httpClient.PostAsync("https://localhost:7289/api/Methods", content);
                //{
                //    string apiResponse = await response.Content.ReadAsStringAsync();
                //    pizzaobj = JsonConvert.DeserializeObject<Product>(apiResponse);
                //}
            }


            return RedirectToAction("Thanking");
        }
        [NoDirectAccess]

        public async Task<IActionResult> Transactions()
        {
            List<Buyer> p = new List<Buyer>();
            var UserId = HttpContext.Session.GetInt32("id");
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("https://localhost:7289/api/Transactions/" + UserId);
                if (res.IsSuccessStatusCode)
                {
                    var Prodres = res.Content.ReadAsStringAsync().Result;
                    p = JsonConvert.DeserializeObject<List<Buyer>>(Prodres);
                }
               
            }
            List<String> s=new List<String>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("https://localhost:7289/api/GetProductName/GetProductName/" + UserId);
                if (res.IsSuccessStatusCode)
                {
                    var Prodres = res.Content.ReadAsStringAsync().Result;
                    s= JsonConvert.DeserializeObject<List<string>>(Prodres);
                }

            }
           



            var mode = new List<string>();
            foreach(var m in p)
            {
                if(m.PaymentMode!=null)
                {
                    mode.Add(m.PaymentMode);
                }
            }
            var mode1 = new List<object>();
            foreach (var m in p)
            {
                if (m.DateofPurchase != null)
                {
                   
                    mode1.Add(m.DateofPurchase);
                }
            }
            var mode2 = new List<object>();
            foreach (var m in p)
            {
                if (m.TotalAmount!= null)
                {
                    mode2.Add(m.TotalAmount);
                }
            }



            ViewBag.PName = s;
            ViewBag.DOP = mode1;
            ViewBag.PM=mode;
            ViewBag.TM=mode2;

Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrugMMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrugMMvc.styles.css" asp-append-version="true" />
     <link rel="stylesheet" href="~/css/Admin.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Melbourne Drugs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Methods" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DrugMMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/AdminLogLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrugMMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrugMMvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/AdminLogin.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Melbourne Drugs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - DrugMMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/UserLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrugMMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrugMMvc.styles.css" asp-append-version="true" />
     <link rel="stylesheet" href="~/css/UserLogLayout.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DrugMMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DrugMMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/UserLogLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrugMMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrugMMvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/UserLogin.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Melbourne Drugs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - DrugMMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrugMMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrugMMvc.styles.css" asp-append-version="true" />
     @*<link rel="stylesheet" href="~/css/UserLogLayout.css" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Melbourne Drugs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DrugMMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>